Develop
MichalNiedziela1601/cinkciarz_training pull request #6
Opened 2017-01-03 11:04 UTC by MichalNiedziela1601

2017-01-03 14:23 UTC, aniaw requested changes

2017-01-03 14:23 UTC, aniaw commented on app/app.run.js
> + */
You should remove this comment.

2017-01-03 14:23 UTC, aniaw commented on app/js/controllers/mainCtrl.js
> +        var stop;
place `var` variable in one place (on top).

2017-01-03 14:23 UTC, aniaw commented on app/js/controllers/mainCtrl.js
> +                return;
I don't like this piece of code.
```
 if (null == oldRate) {
               return;
}
 return buy > oldRate.buy;
```

Check if this works:
```
if(!oldRate) {
     return buy > oldRate.buy;
}
```

2017-01-03 14:23 UTC, aniaw commented on app/js/controllers/mainCtrl.js
> +            if (old.length === 0) {
It is better practice to use

```0 === old.length``` 
instead of
```old.length === 0```

2017-01-03 14:23 UTC, aniaw commented on app/js/controllers/mainCtrl.js
> +            if (null == oldRate) {
same as above

2017-01-03 14:23 UTC, aniaw commented on app/js/controllers/sellCtrl.js
> +            ctrl.sellCost = sellCost;
What is ```sellCost``` variable ?

2017-01-03 14:23 UTC, aniaw commented on app/js/controllers/startCtrl.js
> +                showErrorMessage('Nie wpisałeś wartości');
;)

2017-01-03 14:23 UTC, aniaw commented on app/js/controllers/modalConfirmCtrl.js
>   */
You should remove this comment.

2017-01-03 14:23 UTC, aniaw commented on app/js/controllers/navbarCtrl.js
>   */
You should remove this comment.

2017-01-03 14:23 UTC, aniaw commented on app/js/services/logFactory.js
> + */
You should remove this comment.

2017-01-03 14:23 UTC, aniaw commented on app/js/services/randomCurrencyService.js
> + */
You should remove this comment.

2017-01-03 14:23 UTC, aniaw commented on app/js/services/ratesFactory.js
> + */
You should remove this comment.

2017-01-10 07:31 UTC, MichalNiedziela1601 commented on app/js/controllers/sellCtrl.js
> +            ctrl.sellCost = sellCost;
SellCost is a function which calculate how many pln we will get when sell some other money

2017-01-10 08:38 UTC, aniaw approved these changes

2017-01-10 08:39 UTC, merged